
mysql_db:
  image: mysql
  ports:
  - "3306:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=root
  - MYSQL_DB=graphql_user

graphql_runner:
  build: .
  volumes:
  - ./:/graphql
  command: npm start
  ports:
    - "3000:3000"



