
# mysql_db:
#   image: mysql
#   ports:
#   - "4306:4306"
#   environment:
#   - MYSQL_ROOT_PASSWORD=root
#   - MYSQL_DB=graphql_user

version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: graphql_user
    ports:
      - "3306:3306"
  
  sequelize_runner:
    build: .
    restart: on-failure
    depends_on:
      - db
    command: npm run db:migrate
    # command: ["./waitformysql.sh", " graphql_user", " npm", " run", " db:migrate"]

  graphql_runner:
    build: .
    volumes:
    - ./:/graphql
    command: npm start
    depends_on:
      - sequelize_runner
    ports:
      - "3000:3000"



